# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: ko
title: "비움"
email: likemin0142@gmail.com
description: 수박 겉이 아닌 수박 속에 집중하자.
baseurl: "/" # the optional subpath of your site, e.g. "/blog"
url: "https://biewoom.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
disqus:
  shortname: basically-basic-theme
author:
  name: 유정민
  twitter:
  picture:
twitter_username:
github_username: Biewoom
logo: "/assets/logo/bw_logo.svg" # path of site logo, e.g. "/assets/images/logo.png"
search: true
search_full_content: true
search_provider: # lunr (default), algolia

# Build settings
markdown: kramdown
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
#Collections

collections:
  datastructure:
    output: true
    # permalink: /:collection/:path

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  - scope:
      path: "_ps"
      type: posts
    values:
      layout: post
      read_time: true
  - scope:
      path: "_datastructure"
      type: posts
    values:
      layout: post
      read_time: true
